# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ControlFileDlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ControlFileDlg(object):
    def setupUi(self, ControlFileDlg):
        ControlFileDlg.setObjectName("ControlFileDlg")
        ControlFileDlg.resize(571, 531)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlFileDlg.sizePolicy().hasHeightForWidth())
        ControlFileDlg.setSizePolicy(sizePolicy)
        ControlFileDlg.setMinimumSize(QtCore.QSize(571, 531))
        ControlFileDlg.setMaximumSize(QtCore.QSize(571, 531))
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 551, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tblTemplateInput = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblTemplateInput.setMinimumSize(QtCore.QSize(0, 0))
        self.tblTemplateInput.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblTemplateInput.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblTemplateInput.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblTemplateInput.setWordWrap(False)
        self.tblTemplateInput.setRowCount(100)
        self.tblTemplateInput.setColumnCount(2)
        self.tblTemplateInput.setObjectName("tblTemplateInput")
        item = QtWidgets.QTableWidgetItem()
        self.tblTemplateInput.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblTemplateInput.setHorizontalHeaderItem(1, item)
        self.tblTemplateInput.horizontalHeader().setVisible(True)
        self.tblTemplateInput.horizontalHeader().setCascadingSectionResizes(False)
        self.tblTemplateInput.horizontalHeader().setDefaultSectionSize(110)
        self.tblTemplateInput.horizontalHeader().setHighlightSections(True)
        self.tblTemplateInput.horizontalHeader().setStretchLastSection(False)
        self.tblTemplateInput.verticalHeader().setDefaultSectionSize(20)
        self.tblTemplateInput.verticalHeader().setMinimumSectionSize(20)
        self.tblTemplateInput.verticalHeader().setSortIndicatorShown(False)
        self.tblTemplateInput.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblTemplateInput, 1, 0, 1, 1)
        self.tblInstructionOutput = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblInstructionOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.tblInstructionOutput.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblInstructionOutput.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblInstructionOutput.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblInstructionOutput.setWordWrap(False)
        self.tblInstructionOutput.setRowCount(100)
        self.tblInstructionOutput.setColumnCount(2)
        self.tblInstructionOutput.setObjectName("tblInstructionOutput")
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructionOutput.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructionOutput.setHorizontalHeaderItem(1, item)
        self.tblInstructionOutput.horizontalHeader().setVisible(True)
        self.tblInstructionOutput.horizontalHeader().setCascadingSectionResizes(False)
        self.tblInstructionOutput.horizontalHeader().setDefaultSectionSize(110)
        self.tblInstructionOutput.horizontalHeader().setHighlightSections(True)
        self.tblInstructionOutput.horizontalHeader().setStretchLastSection(False)
        self.tblInstructionOutput.verticalHeader().setDefaultSectionSize(20)
        self.tblInstructionOutput.verticalHeader().setMinimumSectionSize(20)
        self.tblInstructionOutput.verticalHeader().setSortIndicatorShown(False)
        self.tblInstructionOutput.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblInstructionOutput, 3, 0, 1, 1)
        self.tblAttributeType = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblAttributeType.setMinimumSize(QtCore.QSize(0, 0))
        self.tblAttributeType.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblAttributeType.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAttributeType.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblAttributeType.setWordWrap(False)
        self.tblAttributeType.setRowCount(100)
        self.tblAttributeType.setColumnCount(2)
        self.tblAttributeType.setObjectName("tblAttributeType")
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributeType.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributeType.setHorizontalHeaderItem(1, item)
        self.tblAttributeType.horizontalHeader().setVisible(True)
        self.tblAttributeType.horizontalHeader().setCascadingSectionResizes(False)
        self.tblAttributeType.horizontalHeader().setDefaultSectionSize(110)
        self.tblAttributeType.horizontalHeader().setHighlightSections(True)
        self.tblAttributeType.horizontalHeader().setStretchLastSection(False)
        self.tblAttributeType.verticalHeader().setDefaultSectionSize(20)
        self.tblAttributeType.verticalHeader().setMinimumSectionSize(20)
        self.tblAttributeType.verticalHeader().setSortIndicatorShown(False)
        self.tblAttributeType.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblAttributeType, 3, 1, 1, 1)
        self.tblAttributeCode = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblAttributeCode.setMinimumSize(QtCore.QSize(0, 0))
        self.tblAttributeCode.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblAttributeCode.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblAttributeCode.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblAttributeCode.setWordWrap(False)
        self.tblAttributeCode.setRowCount(500)
        self.tblAttributeCode.setColumnCount(2)
        self.tblAttributeCode.setObjectName("tblAttributeCode")
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributeCode.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributeCode.setHorizontalHeaderItem(1, item)
        self.tblAttributeCode.horizontalHeader().setVisible(True)
        self.tblAttributeCode.horizontalHeader().setCascadingSectionResizes(False)
        self.tblAttributeCode.horizontalHeader().setDefaultSectionSize(110)
        self.tblAttributeCode.horizontalHeader().setHighlightSections(True)
        self.tblAttributeCode.horizontalHeader().setStretchLastSection(False)
        self.tblAttributeCode.verticalHeader().setDefaultSectionSize(20)
        self.tblAttributeCode.verticalHeader().setMinimumSectionSize(20)
        self.tblAttributeCode.verticalHeader().setSortIndicatorShown(False)
        self.tblAttributeCode.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblAttributeCode, 1, 1, 1, 1)
        self.Label2_3 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label2_3.sizePolicy().hasHeightForWidth())
        self.Label2_3.setSizePolicy(sizePolicy)
        self.Label2_3.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_3.setObjectName("Label2_3")
        self.gridLayout.addWidget(self.Label2_3, 0, 1, 1, 1)
        self.Label2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label2_2.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_2.setObjectName("Label2_2")
        self.gridLayout.addWidget(self.Label2_2, 0, 0, 1, 1)
        self.Label2_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label2_4.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_4.setObjectName("Label2_4")
        self.gridLayout.addWidget(self.Label2_4, 2, 0, 1, 1)
        self.Label2_5 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label2_5.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_5.setObjectName("Label2_5")
        self.gridLayout.addWidget(self.Label2_5, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 551, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Label2.setMinimumSize(QtCore.QSize(379, 0))
        self.Label2.setObjectName("Label2")
        self.verticalLayout_3.addWidget(self.Label2)
        self.cmbBaseLayer = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cmbBaseLayer.setObjectName("cmbBaseLayer")
        self.verticalLayout_3.addWidget(self.cmbBaseLayer)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 551, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Label3.setObjectName("Label3")
        self.verticalLayout_4.addWidget(self.Label3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbxModelDirectory = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.tbxModelDirectory.setObjectName("tbxModelDirectory")
        self.horizontalLayout_2.addWidget(self.tbxModelDirectory)
        self.btnBrowse = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout_2.addWidget(self.btnBrowse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 470, 551, 51))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Label3_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Label3_2.setObjectName("Label3_2")
        self.verticalLayout_5.addWidget(self.Label3_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tbxCommandLine = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxCommandLine.setObjectName("tbxCommandLine")
        self.horizontalLayout_3.addWidget(self.tbxCommandLine)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(ControlFileDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 10, 291, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_4.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_4.addWidget(self.btnExit)

        self.retranslateUi(ControlFileDlg)
        QtCore.QMetaObject.connectSlotsByName(ControlFileDlg)

    def retranslateUi(self, ControlFileDlg):
        _translate = QtCore.QCoreApplication.translate
        ControlFileDlg.setWindowTitle(_translate("ControlFileDlg", "Control File Creator"))
        item = self.tblTemplateInput.horizontalHeaderItem(0)
        item.setText(_translate("ControlFileDlg", "Template File"))
        item = self.tblTemplateInput.horizontalHeaderItem(1)
        item.setText(_translate("ControlFileDlg", "Input File"))
        item = self.tblInstructionOutput.horizontalHeaderItem(0)
        item.setText(_translate("ControlFileDlg", "Instruction File"))
        item = self.tblInstructionOutput.horizontalHeaderItem(1)
        item.setText(_translate("ControlFileDlg", "Output File"))
        item = self.tblAttributeType.horizontalHeaderItem(0)
        item.setText(_translate("ControlFileDlg", "Output Attribute"))
        item = self.tblAttributeType.horizontalHeaderItem(1)
        item.setText(_translate("ControlFileDlg", "Type"))
        item = self.tblAttributeCode.horizontalHeaderItem(0)
        item.setText(_translate("ControlFileDlg", "Input Attribute"))
        item = self.tblAttributeCode.horizontalHeaderItem(1)
        item.setText(_translate("ControlFileDlg", "Code"))
        self.Label2_3.setText(_translate("ControlFileDlg", "Specify Input Attribute/Code Relations:"))
        self.Label2_2.setText(_translate("ControlFileDlg", "Specify Model Input File Relations:"))
        self.Label2_4.setText(_translate("ControlFileDlg", "Specify Model Output File Relations:"))
        self.Label2_5.setText(_translate("ControlFileDlg", "Specify Output Attribute/Type:"))
        self.Label2.setText(_translate("ControlFileDlg", "Specify Base Layer Name:"))
        self.Label3.setText(_translate("ControlFileDlg", "Specify Model Working Directory:"))
        self.tbxModelDirectory.setToolTip(_translate("ControlFileDlg", "Give the filepath and filename of the output shapefile"))
        self.btnBrowse.setToolTip(_translate("ControlFileDlg", "Gives dialog box for selecting output filepath and filename."))
        self.btnBrowse.setText(_translate("ControlFileDlg", "Browse"))
        self.Label3_2.setText(_translate("ControlFileDlg", "Specify System Command:"))
        self.tbxCommandLine.setToolTip(_translate("ControlFileDlg", "Give the filepath and filename of the output shapefile"))
        self.btnLoad.setText(_translate("ControlFileDlg", "Load File"))
        self.btnSave.setText(_translate("ControlFileDlg", "Save File"))
        self.btnExit.setText(_translate("ControlFileDlg", "Exit"))

