# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ControlFileDlg.ui'
#
# Created: Mon Nov 04 09:34:04 2013
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from qgis.PyQt import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ControlFileDlg(object):
    def setupUi(self, ControlFileDlg):
        ControlFileDlg.setObjectName(_fromUtf8("ControlFileDlg"))
        ControlFileDlg.resize(571, 531)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ControlFileDlg.sizePolicy().hasHeightForWidth())
        ControlFileDlg.setSizePolicy(sizePolicy)
        ControlFileDlg.setMinimumSize(QtCore.QSize(571, 531))
        ControlFileDlg.setMaximumSize(QtCore.QSize(571, 531))
        self.verticalLayoutWidget_2 = QtGui.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 551, 291))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblTemplateInput = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.tblTemplateInput.setMinimumSize(QtCore.QSize(0, 0))
        self.tblTemplateInput.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tblTemplateInput.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblTemplateInput.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblTemplateInput.setWordWrap(False)
        self.tblTemplateInput.setRowCount(100)
        self.tblTemplateInput.setColumnCount(2)
        self.tblTemplateInput.setObjectName(_fromUtf8("tblTemplateInput"))
        self.tblTemplateInput.setColumnCount(2)
        self.tblTemplateInput.setRowCount(100)
        item = QtGui.QTableWidgetItem()
        self.tblTemplateInput.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblTemplateInput.setHorizontalHeaderItem(1, item)
        self.tblTemplateInput.horizontalHeader().setVisible(True)
        self.tblTemplateInput.horizontalHeader().setCascadingSectionResizes(False)
        self.tblTemplateInput.horizontalHeader().setDefaultSectionSize(110)
        self.tblTemplateInput.horizontalHeader().setHighlightSections(True)
        self.tblTemplateInput.horizontalHeader().setStretchLastSection(False)
        self.tblTemplateInput.verticalHeader().setDefaultSectionSize(20)
        self.tblTemplateInput.verticalHeader().setMinimumSectionSize(20)
        self.tblTemplateInput.verticalHeader().setSortIndicatorShown(False)
        self.tblTemplateInput.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblTemplateInput, 1, 0, 1, 1)
        self.tblInstructionOutput = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.tblInstructionOutput.setMinimumSize(QtCore.QSize(0, 0))
        self.tblInstructionOutput.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tblInstructionOutput.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblInstructionOutput.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblInstructionOutput.setWordWrap(False)
        self.tblInstructionOutput.setRowCount(100)
        self.tblInstructionOutput.setColumnCount(2)
        self.tblInstructionOutput.setObjectName(_fromUtf8("tblInstructionOutput"))
        self.tblInstructionOutput.setColumnCount(2)
        self.tblInstructionOutput.setRowCount(100)
        item = QtGui.QTableWidgetItem()
        self.tblInstructionOutput.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblInstructionOutput.setHorizontalHeaderItem(1, item)
        self.tblInstructionOutput.horizontalHeader().setVisible(True)
        self.tblInstructionOutput.horizontalHeader().setCascadingSectionResizes(False)
        self.tblInstructionOutput.horizontalHeader().setDefaultSectionSize(110)
        self.tblInstructionOutput.horizontalHeader().setHighlightSections(True)
        self.tblInstructionOutput.horizontalHeader().setStretchLastSection(False)
        self.tblInstructionOutput.verticalHeader().setDefaultSectionSize(20)
        self.tblInstructionOutput.verticalHeader().setMinimumSectionSize(20)
        self.tblInstructionOutput.verticalHeader().setSortIndicatorShown(False)
        self.tblInstructionOutput.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblInstructionOutput, 3, 0, 1, 1)
        self.tblAttributeType = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.tblAttributeType.setMinimumSize(QtCore.QSize(0, 0))
        self.tblAttributeType.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tblAttributeType.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblAttributeType.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblAttributeType.setWordWrap(False)
        self.tblAttributeType.setRowCount(100)
        self.tblAttributeType.setColumnCount(2)
        self.tblAttributeType.setObjectName(_fromUtf8("tblAttributeType"))
        self.tblAttributeType.setColumnCount(2)
        self.tblAttributeType.setRowCount(100)
        item = QtGui.QTableWidgetItem()
        self.tblAttributeType.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAttributeType.setHorizontalHeaderItem(1, item)
        self.tblAttributeType.horizontalHeader().setVisible(True)
        self.tblAttributeType.horizontalHeader().setCascadingSectionResizes(False)
        self.tblAttributeType.horizontalHeader().setDefaultSectionSize(110)
        self.tblAttributeType.horizontalHeader().setHighlightSections(True)
        self.tblAttributeType.horizontalHeader().setStretchLastSection(False)
        self.tblAttributeType.verticalHeader().setDefaultSectionSize(20)
        self.tblAttributeType.verticalHeader().setMinimumSectionSize(20)
        self.tblAttributeType.verticalHeader().setSortIndicatorShown(False)
        self.tblAttributeType.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblAttributeType, 3, 1, 1, 1)
        self.tblAttributeCode = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.tblAttributeCode.setMinimumSize(QtCore.QSize(0, 0))
        self.tblAttributeCode.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tblAttributeCode.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblAttributeCode.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblAttributeCode.setWordWrap(False)
        self.tblAttributeCode.setRowCount(500)
        self.tblAttributeCode.setColumnCount(2)
        self.tblAttributeCode.setObjectName(_fromUtf8("tblAttributeCode"))
        self.tblAttributeCode.setColumnCount(2)
        self.tblAttributeCode.setRowCount(500)
        item = QtGui.QTableWidgetItem()
        self.tblAttributeCode.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblAttributeCode.setHorizontalHeaderItem(1, item)
        self.tblAttributeCode.horizontalHeader().setVisible(True)
        self.tblAttributeCode.horizontalHeader().setCascadingSectionResizes(False)
        self.tblAttributeCode.horizontalHeader().setDefaultSectionSize(110)
        self.tblAttributeCode.horizontalHeader().setHighlightSections(True)
        self.tblAttributeCode.horizontalHeader().setStretchLastSection(False)
        self.tblAttributeCode.verticalHeader().setDefaultSectionSize(20)
        self.tblAttributeCode.verticalHeader().setMinimumSectionSize(20)
        self.tblAttributeCode.verticalHeader().setSortIndicatorShown(False)
        self.tblAttributeCode.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblAttributeCode, 1, 1, 1, 1)
        self.Label2_3 = QtGui.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label2_3.sizePolicy().hasHeightForWidth())
        self.Label2_3.setSizePolicy(sizePolicy)
        self.Label2_3.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_3.setObjectName(_fromUtf8("Label2_3"))
        self.gridLayout.addWidget(self.Label2_3, 0, 1, 1, 1)
        self.Label2_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Label2_2.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_2.setObjectName(_fromUtf8("Label2_2"))
        self.gridLayout.addWidget(self.Label2_2, 0, 0, 1, 1)
        self.Label2_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Label2_4.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_4.setObjectName(_fromUtf8("Label2_4"))
        self.gridLayout.addWidget(self.Label2_4, 2, 0, 1, 1)
        self.Label2_5 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Label2_5.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_5.setObjectName(_fromUtf8("Label2_5"))
        self.gridLayout.addWidget(self.Label2_5, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayoutWidget_3 = QtGui.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 551, 51))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Label2 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.Label2.setMinimumSize(QtCore.QSize(379, 0))
        self.Label2.setObjectName(_fromUtf8("Label2"))
        self.verticalLayout_3.addWidget(self.Label2)
        self.cmbBaseLayer = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cmbBaseLayer.setObjectName(_fromUtf8("cmbBaseLayer"))
        self.verticalLayout_3.addWidget(self.cmbBaseLayer)
        self.verticalLayoutWidget_4 = QtGui.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 551, 51))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Label3 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.Label3.setObjectName(_fromUtf8("Label3"))
        self.verticalLayout_4.addWidget(self.Label3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tbxModelDirectory = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.tbxModelDirectory.setObjectName(_fromUtf8("tbxModelDirectory"))
        self.horizontalLayout_2.addWidget(self.tbxModelDirectory)
        self.btnBrowse = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout_2.addWidget(self.btnBrowse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_5 = QtGui.QWidget(ControlFileDlg)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 470, 551, 51))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Label3_2 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.Label3_2.setObjectName(_fromUtf8("Label3_2"))
        self.verticalLayout_5.addWidget(self.Label3_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.tbxCommandLine = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxCommandLine.setObjectName(_fromUtf8("tbxCommandLine"))
        self.horizontalLayout_3.addWidget(self.tbxCommandLine)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayoutWidget = QtGui.QWidget(ControlFileDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(140, 10, 291, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnLoad = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.horizontalLayout_4.addWidget(self.btnLoad)
        self.btnSave = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnExit = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.horizontalLayout_4.addWidget(self.btnExit)

        self.retranslateUi(ControlFileDlg)
        QtCore.QMetaObject.connectSlotsByName(ControlFileDlg)

    def retranslateUi(self, ControlFileDlg):
        ControlFileDlg.setWindowTitle(QtGui.QApplication.translate("ControlFileDlg", "Control File Creator", None, QtGui.QApplication.UnicodeUTF8))
        self.tblTemplateInput.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ControlFileDlg", "Template File", None, QtGui.QApplication.UnicodeUTF8))
        self.tblTemplateInput.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ControlFileDlg", "Input File", None, QtGui.QApplication.UnicodeUTF8))
        self.tblInstructionOutput.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ControlFileDlg", "Instruction File", None, QtGui.QApplication.UnicodeUTF8))
        self.tblInstructionOutput.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ControlFileDlg", "Output File", None, QtGui.QApplication.UnicodeUTF8))
        self.tblAttributeType.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ControlFileDlg", "Output Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.tblAttributeType.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ControlFileDlg", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tblAttributeCode.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("ControlFileDlg", "Input Attribute", None, QtGui.QApplication.UnicodeUTF8))
        self.tblAttributeCode.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("ControlFileDlg", "Code", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2_3.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify Input Attribute/Code Relations:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2_2.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify Model Input File Relations:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2_4.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify Model Output File Relations:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2_5.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify Output Attribute/Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify Base Layer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label3.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify Model Working Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxModelDirectory.setToolTip(QtGui.QApplication.translate("ControlFileDlg", "Give the filepath and filename of the output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setToolTip(QtGui.QApplication.translate("ControlFileDlg", "Gives dialog box for selecting output filepath and filename.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("ControlFileDlg", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.Label3_2.setText(QtGui.QApplication.translate("ControlFileDlg", "Specify System Command:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxCommandLine.setToolTip(QtGui.QApplication.translate("ControlFileDlg", "Give the filepath and filename of the output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("ControlFileDlg", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("ControlFileDlg", "Save File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("ControlFileDlg", "Exit", None, QtGui.QApplication.UnicodeUTF8))

