# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_GeoprocessorDlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_GeoprocessorDlg(object):
    def setupUi(self, GeoprocessorDlg):
        GeoprocessorDlg.setObjectName("GeoprocessorDlg")
        GeoprocessorDlg.resize(401, 381)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GeoprocessorDlg.sizePolicy().hasHeightForWidth())
        GeoprocessorDlg.setSizePolicy(sizePolicy)
        GeoprocessorDlg.setMinimumSize(QtCore.QSize(401, 381))
        GeoprocessorDlg.setMaximumSize(QtCore.QSize(401, 381))
        self.verticalLayoutWidget = QtWidgets.QWidget(GeoprocessorDlg)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 130, 381, 51))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label1 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Label1.setMinimumSize(QtCore.QSize(379, 0))
        self.Label1.setObjectName("Label1")
        self.verticalLayout.addWidget(self.Label1)
        self.cmbProcessLayer = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.cmbProcessLayer.setObjectName("cmbProcessLayer")
        self.verticalLayout.addWidget(self.cmbProcessLayer)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(GeoprocessorDlg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 381, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Label2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label2.setMinimumSize(QtCore.QSize(379, 0))
        self.Label2.setObjectName("Label2")
        self.verticalLayout_2.addWidget(self.Label2)
        self.cmbBaseLayer = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        self.cmbBaseLayer.setObjectName("cmbBaseLayer")
        self.verticalLayout_2.addWidget(self.cmbBaseLayer)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(GeoprocessorDlg)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 330, 381, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ProgressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.ProgressBar.setObjectName("ProgressBar")
        self.horizontalLayout_3.addWidget(self.ProgressBar)
        self.btnRun = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout_3.addWidget(self.btnRun)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_3.addWidget(self.btnExit)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(GeoprocessorDlg)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 190, 381, 131))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label1_2 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Label1_2.setMinimumSize(QtCore.QSize(379, 0))
        self.Label1_2.setObjectName("Label1_2")
        self.verticalLayout_4.addWidget(self.Label1_2)
        self.listFields = QtWidgets.QListWidget(self.verticalLayoutWidget_4)
        self.listFields.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listFields.setObjectName("listFields")
        self.verticalLayout_4.addWidget(self.listFields)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(GeoprocessorDlg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 381, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Label3.setObjectName("Label3")
        self.verticalLayout_3.addWidget(self.Label3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmbObjective = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cmbObjective.setObjectName("cmbObjective")
        self.horizontalLayout_2.addWidget(self.cmbObjective)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(GeoprocessorDlg)
        QtCore.QMetaObject.connectSlotsByName(GeoprocessorDlg)

    def retranslateUi(self, GeoprocessorDlg):
        _translate = QtCore.QCoreApplication.translate
        GeoprocessorDlg.setWindowTitle(_translate("GeoprocessorDlg", "Vector Geoprocessor"))
        self.Label1.setText(_translate("GeoprocessorDlg", "Select Layer To Process:"))
        self.cmbProcessLayer.setToolTip(_translate("GeoprocessorDlg", "Select the layer to process."))
        self.Label2.setText(_translate("GeoprocessorDlg", "Select Base Layer:"))
        self.cmbBaseLayer.setToolTip(_translate("GeoprocessorDlg", "Select the polygon base layer."))
        self.btnRun.setText(_translate("GeoprocessorDlg", "Run"))
        self.btnExit.setText(_translate("GeoprocessorDlg", "Exit"))
        self.Label1_2.setText(_translate("GeoprocessorDlg", "Select Data Fields To Process:"))
        self.Label3.setText(_translate("GeoprocessorDlg", "Select Processing Objective:"))
        self.cmbObjective.setToolTip(_translate("GeoprocessorDlg", "Select the processing objective."))

