# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OptimizationFileDlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OptimizationFileDlg(object):
    def setupUi(self, OptimizationFileDlg):
        OptimizationFileDlg.setObjectName("OptimizationFileDlg")
        OptimizationFileDlg.resize(521, 681)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptimizationFileDlg.sizePolicy().hasHeightForWidth())
        OptimizationFileDlg.setSizePolicy(sizePolicy)
        OptimizationFileDlg.setMinimumSize(QtCore.QSize(521, 681))
        OptimizationFileDlg.setMaximumSize(QtCore.QSize(521, 681))
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 501, 291))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tblOptAttributes = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblOptAttributes.setMinimumSize(QtCore.QSize(0, 0))
        self.tblOptAttributes.setMaximumSize(QtCore.QSize(497, 16777215))
        self.tblOptAttributes.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblOptAttributes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblOptAttributes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblOptAttributes.setWordWrap(False)
        self.tblOptAttributes.setRowCount(100)
        self.tblOptAttributes.setColumnCount(5)
        self.tblOptAttributes.setObjectName("tblOptAttributes")
        item = QtWidgets.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(4, item)
        self.tblOptAttributes.horizontalHeader().setVisible(True)
        self.tblOptAttributes.horizontalHeader().setCascadingSectionResizes(False)
        self.tblOptAttributes.horizontalHeader().setDefaultSectionSize(89)
        self.tblOptAttributes.horizontalHeader().setHighlightSections(True)
        self.tblOptAttributes.horizontalHeader().setStretchLastSection(False)
        self.tblOptAttributes.verticalHeader().setDefaultSectionSize(20)
        self.tblOptAttributes.verticalHeader().setMinimumSectionSize(20)
        self.tblOptAttributes.verticalHeader().setSortIndicatorShown(False)
        self.tblOptAttributes.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblOptAttributes, 1, 0, 1, 1)
        self.tblObjAttributes = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.tblObjAttributes.setMinimumSize(QtCore.QSize(0, 0))
        self.tblObjAttributes.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblObjAttributes.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblObjAttributes.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tblObjAttributes.setWordWrap(False)
        self.tblObjAttributes.setRowCount(100)
        self.tblObjAttributes.setColumnCount(3)
        self.tblObjAttributes.setObjectName("tblObjAttributes")
        item = QtWidgets.QTableWidgetItem()
        self.tblObjAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblObjAttributes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblObjAttributes.setHorizontalHeaderItem(2, item)
        self.tblObjAttributes.horizontalHeader().setVisible(True)
        self.tblObjAttributes.horizontalHeader().setCascadingSectionResizes(False)
        self.tblObjAttributes.horizontalHeader().setDefaultSectionSize(110)
        self.tblObjAttributes.horizontalHeader().setHighlightSections(True)
        self.tblObjAttributes.horizontalHeader().setStretchLastSection(False)
        self.tblObjAttributes.verticalHeader().setDefaultSectionSize(20)
        self.tblObjAttributes.verticalHeader().setMinimumSectionSize(20)
        self.tblObjAttributes.verticalHeader().setSortIndicatorShown(False)
        self.tblObjAttributes.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblObjAttributes, 3, 0, 1, 1)
        self.Label2_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label2_2.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_2.setObjectName("Label2_2")
        self.gridLayout.addWidget(self.Label2_2, 0, 0, 1, 1)
        self.Label2_4 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.Label2_4.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_4.setObjectName("Label2_4")
        self.gridLayout.addWidget(self.Label2_4, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 501, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label2 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Label2.setMinimumSize(QtCore.QSize(379, 0))
        self.Label2.setObjectName("Label2")
        self.verticalLayout_3.addWidget(self.Label2)
        self.cmbBaseLayer = QtWidgets.QComboBox(self.verticalLayoutWidget_3)
        self.cmbBaseLayer.setObjectName("cmbBaseLayer")
        self.verticalLayout_3.addWidget(self.cmbBaseLayer)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 501, 51))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Label3 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.Label3.setObjectName("Label3")
        self.verticalLayout_4.addWidget(self.Label3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbxControlFile = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        self.tbxControlFile.setObjectName("tbxControlFile")
        self.horizontalLayout_2.addWidget(self.tbxControlFile)
        self.btnBrowse = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout_2.addWidget(self.btnBrowse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 470, 501, 201))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Label3_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.Label3_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Label3_2.setObjectName("Label3_2")
        self.verticalLayout_5.addWidget(self.Label3_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.tbxTf = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxTf.setObjectName("tbxTf")
        self.gridLayout_2.addWidget(self.tbxTf, 1, 2, 1, 1)
        self.tbxm = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxm.setObjectName("tbxm")
        self.gridLayout_2.addWidget(self.tbxm, 1, 4, 1, 1)
        self.tbxT0 = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxT0.setObjectName("tbxT0")
        self.gridLayout_2.addWidget(self.tbxT0, 0, 2, 1, 1)
        self.tbxDwell = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxDwell.setObjectName("tbxDwell")
        self.gridLayout_2.addWidget(self.tbxDwell, 2, 2, 1, 1)
        self.tbxTolerance = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxTolerance.setObjectName("tbxTolerance")
        self.gridLayout_2.addWidget(self.tbxTolerance, 3, 2, 1, 1)
        self.tbxMaxEval = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxMaxEval.setObjectName("tbxMaxEval")
        self.gridLayout_2.addWidget(self.tbxMaxEval, 4, 2, 1, 1)
        self.tbxMaxIter = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxMaxIter.setObjectName("tbxMaxIter")
        self.gridLayout_2.addWidget(self.tbxMaxIter, 5, 2, 1, 1)
        self.tbxMaxAccept = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxMaxAccept.setObjectName("tbxMaxAccept")
        self.gridLayout_2.addWidget(self.tbxMaxAccept, 0, 4, 1, 1)
        self.tbxn = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxn.setObjectName("tbxn")
        self.gridLayout_2.addWidget(self.tbxn, 2, 4, 1, 1)
        self.tbxQuench = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxQuench.setObjectName("tbxQuench")
        self.gridLayout_2.addWidget(self.tbxQuench, 3, 4, 1, 1)
        self.tbxBoltzmann = QtWidgets.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxBoltzmann.setObjectName("tbxBoltzmann")
        self.gridLayout_2.addWidget(self.tbxBoltzmann, 4, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayoutWidget = QtWidgets.QWidget(OptimizationFileDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 10, 281, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_4.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_4.addWidget(self.btnExit)

        self.retranslateUi(OptimizationFileDlg)
        QtCore.QMetaObject.connectSlotsByName(OptimizationFileDlg)

    def retranslateUi(self, OptimizationFileDlg):
        _translate = QtCore.QCoreApplication.translate
        OptimizationFileDlg.setWindowTitle(_translate("OptimizationFileDlg", "Optimization File Creator"))
        item = self.tblOptAttributes.horizontalHeaderItem(0)
        item.setText(_translate("OptimizationFileDlg", "Attribute"))
        item = self.tblOptAttributes.horizontalHeaderItem(1)
        item.setText(_translate("OptimizationFileDlg", "Initial"))
        item = self.tblOptAttributes.horizontalHeaderItem(2)
        item.setText(_translate("OptimizationFileDlg", "Lower"))
        item = self.tblOptAttributes.horizontalHeaderItem(3)
        item.setText(_translate("OptimizationFileDlg", "Upper"))
        item = self.tblOptAttributes.horizontalHeaderItem(4)
        item.setText(_translate("OptimizationFileDlg", "Code"))
        item = self.tblObjAttributes.horizontalHeaderItem(0)
        item.setText(_translate("OptimizationFileDlg", "Measured"))
        item = self.tblObjAttributes.horizontalHeaderItem(1)
        item.setText(_translate("OptimizationFileDlg", "Simulated"))
        item = self.tblObjAttributes.horizontalHeaderItem(2)
        item.setText(_translate("OptimizationFileDlg", "Factor"))
        self.Label2_2.setText(_translate("OptimizationFileDlg", "Specify Attributes to Optimize:"))
        self.Label2_4.setText(_translate("OptimizationFileDlg", "Specify Measured and Simulated Attribute Relations:"))
        self.Label2.setText(_translate("OptimizationFileDlg", "Specify Base Layer Name:"))
        self.Label3.setText(_translate("OptimizationFileDlg", "Specify Simulation Control File:"))
        self.tbxControlFile.setToolTip(_translate("OptimizationFileDlg", "Give the filepath and filename of the output shapefile"))
        self.btnBrowse.setToolTip(_translate("OptimizationFileDlg", "Gives dialog box for selecting output filepath and filename."))
        self.btnBrowse.setText(_translate("OptimizationFileDlg", "Browse"))
        self.Label3_2.setText(_translate("OptimizationFileDlg", "Specify Optimization Parameters:"))
        self.label.setText(_translate("OptimizationFileDlg", "Initial Temperature:"))
        self.label_2.setText(_translate("OptimizationFileDlg", "Dwell (Evals/Par/T):"))
        self.label_3.setText(_translate("OptimizationFileDlg", "Final Temperature:"))
        self.label_4.setText(_translate("OptimizationFileDlg", "Max Accepted:"))
        self.label_5.setText(_translate("OptimizationFileDlg", "m"))
        self.label_6.setText(_translate("OptimizationFileDlg", "n"))
        self.label_7.setText(_translate("OptimizationFileDlg", "Tolerance:"))
        self.label_8.setText(_translate("OptimizationFileDlg", "Quench"))
        self.label_9.setText(_translate("OptimizationFileDlg", "Max Evaluations:"))
        self.label_10.setText(_translate("OptimizationFileDlg", "Boltzmann"))
        self.label_11.setText(_translate("OptimizationFileDlg", "Max Iterations:"))
        self.tbxTf.setText(_translate("OptimizationFileDlg", "None"))
        self.tbxm.setText(_translate("OptimizationFileDlg", "1.0"))
        self.tbxT0.setText(_translate("OptimizationFileDlg", "10.0"))
        self.tbxDwell.setText(_translate("OptimizationFileDlg", "10"))
        self.tbxTolerance.setText(_translate("OptimizationFileDlg", "0.05"))
        self.tbxMaxEval.setText(_translate("OptimizationFileDlg", "None"))
        self.tbxMaxIter.setText(_translate("OptimizationFileDlg", "20"))
        self.tbxMaxAccept.setText(_translate("OptimizationFileDlg", "None"))
        self.tbxn.setText(_translate("OptimizationFileDlg", "1.0"))
        self.tbxQuench.setText(_translate("OptimizationFileDlg", "1.0"))
        self.tbxBoltzmann.setText(_translate("OptimizationFileDlg", "0.05"))
        self.btnLoad.setText(_translate("OptimizationFileDlg", "Load File"))
        self.btnSave.setText(_translate("OptimizationFileDlg", "Save File"))
        self.btnExit.setText(_translate("OptimizationFileDlg", "Exit"))

