# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OptimizationFileDlg.ui'
#
# Created: Wed Sep 24 14:18:42 2014
#      by: PyQt4 UI code generator 4.9
#
# WARNING! All changes made in this file will be lost!

from builtins import object
from qgis.PyQt import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OptimizationFileDlg(object):
    def setupUi(self, OptimizationFileDlg):
        OptimizationFileDlg.setObjectName(_fromUtf8("OptimizationFileDlg"))
        OptimizationFileDlg.resize(521, 681)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OptimizationFileDlg.sizePolicy().hasHeightForWidth())
        OptimizationFileDlg.setSizePolicy(sizePolicy)
        OptimizationFileDlg.setMinimumSize(QtCore.QSize(521, 681))
        OptimizationFileDlg.setMaximumSize(QtCore.QSize(521, 681))
        self.verticalLayoutWidget_2 = QtGui.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 170, 501, 291))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tblOptAttributes = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.tblOptAttributes.setMinimumSize(QtCore.QSize(0, 0))
        self.tblOptAttributes.setMaximumSize(QtCore.QSize(497, 16777215))
        self.tblOptAttributes.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tblOptAttributes.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblOptAttributes.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblOptAttributes.setWordWrap(False)
        self.tblOptAttributes.setRowCount(100)
        self.tblOptAttributes.setColumnCount(5)
        self.tblOptAttributes.setObjectName(_fromUtf8("tblOptAttributes"))
        item = QtGui.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tblOptAttributes.setHorizontalHeaderItem(4, item)
        self.tblOptAttributes.horizontalHeader().setVisible(True)
        self.tblOptAttributes.horizontalHeader().setCascadingSectionResizes(False)
        self.tblOptAttributes.horizontalHeader().setDefaultSectionSize(89)
        self.tblOptAttributes.horizontalHeader().setHighlightSections(True)
        self.tblOptAttributes.horizontalHeader().setStretchLastSection(False)
        self.tblOptAttributes.verticalHeader().setDefaultSectionSize(20)
        self.tblOptAttributes.verticalHeader().setMinimumSectionSize(20)
        self.tblOptAttributes.verticalHeader().setSortIndicatorShown(False)
        self.tblOptAttributes.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblOptAttributes, 1, 0, 1, 1)
        self.tblObjAttributes = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.tblObjAttributes.setMinimumSize(QtCore.QSize(0, 0))
        self.tblObjAttributes.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tblObjAttributes.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblObjAttributes.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.tblObjAttributes.setWordWrap(False)
        self.tblObjAttributes.setRowCount(100)
        self.tblObjAttributes.setColumnCount(3)
        self.tblObjAttributes.setObjectName(_fromUtf8("tblObjAttributes"))
        item = QtGui.QTableWidgetItem()
        self.tblObjAttributes.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tblObjAttributes.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tblObjAttributes.setHorizontalHeaderItem(2, item)
        self.tblObjAttributes.horizontalHeader().setVisible(True)
        self.tblObjAttributes.horizontalHeader().setCascadingSectionResizes(False)
        self.tblObjAttributes.horizontalHeader().setDefaultSectionSize(110)
        self.tblObjAttributes.horizontalHeader().setHighlightSections(True)
        self.tblObjAttributes.horizontalHeader().setStretchLastSection(False)
        self.tblObjAttributes.verticalHeader().setDefaultSectionSize(20)
        self.tblObjAttributes.verticalHeader().setMinimumSectionSize(20)
        self.tblObjAttributes.verticalHeader().setSortIndicatorShown(False)
        self.tblObjAttributes.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.tblObjAttributes, 3, 0, 1, 1)
        self.Label2_2 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Label2_2.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_2.setObjectName(_fromUtf8("Label2_2"))
        self.gridLayout.addWidget(self.Label2_2, 0, 0, 1, 1)
        self.Label2_4 = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.Label2_4.setMinimumSize(QtCore.QSize(220, 0))
        self.Label2_4.setObjectName(_fromUtf8("Label2_4"))
        self.gridLayout.addWidget(self.Label2_4, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayoutWidget_3 = QtGui.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 110, 501, 51))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.Label2 = QtGui.QLabel(self.verticalLayoutWidget_3)
        self.Label2.setMinimumSize(QtCore.QSize(379, 0))
        self.Label2.setObjectName(_fromUtf8("Label2"))
        self.verticalLayout_3.addWidget(self.Label2)
        self.cmbBaseLayer = QtGui.QComboBox(self.verticalLayoutWidget_3)
        self.cmbBaseLayer.setObjectName(_fromUtf8("cmbBaseLayer"))
        self.verticalLayout_3.addWidget(self.cmbBaseLayer)
        self.verticalLayoutWidget_4 = QtGui.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 50, 501, 51))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.Label3 = QtGui.QLabel(self.verticalLayoutWidget_4)
        self.Label3.setObjectName(_fromUtf8("Label3"))
        self.verticalLayout_4.addWidget(self.Label3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tbxControlFile = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.tbxControlFile.setObjectName(_fromUtf8("tbxControlFile"))
        self.horizontalLayout_2.addWidget(self.tbxControlFile)
        self.btnBrowse = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.horizontalLayout_2.addWidget(self.btnBrowse)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayoutWidget_5 = QtGui.QWidget(OptimizationFileDlg)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 470, 501, 201))
        self.verticalLayoutWidget_5.setObjectName(_fromUtf8("verticalLayoutWidget_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.Label3_2 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.Label3_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.Label3_2.setObjectName(_fromUtf8("Label3_2"))
        self.verticalLayout_5.addWidget(self.Label3_2)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 3, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 4, 3, 1, 1)
        self.label_11 = QtGui.QLabel(self.verticalLayoutWidget_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 5, 0, 1, 1)
        self.tbxTf = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxTf.setObjectName(_fromUtf8("tbxTf"))
        self.gridLayout_2.addWidget(self.tbxTf, 1, 2, 1, 1)
        self.tbxm = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxm.setObjectName(_fromUtf8("tbxm"))
        self.gridLayout_2.addWidget(self.tbxm, 1, 4, 1, 1)
        self.tbxT0 = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxT0.setObjectName(_fromUtf8("tbxT0"))
        self.gridLayout_2.addWidget(self.tbxT0, 0, 2, 1, 1)
        self.tbxDwell = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxDwell.setObjectName(_fromUtf8("tbxDwell"))
        self.gridLayout_2.addWidget(self.tbxDwell, 2, 2, 1, 1)
        self.tbxTolerance = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxTolerance.setObjectName(_fromUtf8("tbxTolerance"))
        self.gridLayout_2.addWidget(self.tbxTolerance, 3, 2, 1, 1)
        self.tbxMaxEval = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxMaxEval.setObjectName(_fromUtf8("tbxMaxEval"))
        self.gridLayout_2.addWidget(self.tbxMaxEval, 4, 2, 1, 1)
        self.tbxMaxIter = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxMaxIter.setObjectName(_fromUtf8("tbxMaxIter"))
        self.gridLayout_2.addWidget(self.tbxMaxIter, 5, 2, 1, 1)
        self.tbxMaxAccept = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxMaxAccept.setObjectName(_fromUtf8("tbxMaxAccept"))
        self.gridLayout_2.addWidget(self.tbxMaxAccept, 0, 4, 1, 1)
        self.tbxn = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxn.setObjectName(_fromUtf8("tbxn"))
        self.gridLayout_2.addWidget(self.tbxn, 2, 4, 1, 1)
        self.tbxQuench = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxQuench.setObjectName(_fromUtf8("tbxQuench"))
        self.gridLayout_2.addWidget(self.tbxQuench, 3, 4, 1, 1)
        self.tbxBoltzmann = QtGui.QLineEdit(self.verticalLayoutWidget_5)
        self.tbxBoltzmann.setObjectName(_fromUtf8("tbxBoltzmann"))
        self.gridLayout_2.addWidget(self.tbxBoltzmann, 4, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.horizontalLayoutWidget = QtGui.QWidget(OptimizationFileDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(120, 10, 281, 31))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnLoad = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.horizontalLayout_4.addWidget(self.btnLoad)
        self.btnSave = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnExit = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setObjectName(_fromUtf8("btnExit"))
        self.horizontalLayout_4.addWidget(self.btnExit)

        self.retranslateUi(OptimizationFileDlg)
        QtCore.QMetaObject.connectSlotsByName(OptimizationFileDlg)

    def retranslateUi(self, OptimizationFileDlg):
        OptimizationFileDlg.setWindowTitle(QtGui.QApplication.translate("OptimizationFileDlg", "Optimization File Creator", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblOptAttributes.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Attribute", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblOptAttributes.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Initial", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblOptAttributes.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Lower", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblOptAttributes.horizontalHeaderItem(3)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Upper", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblOptAttributes.horizontalHeaderItem(4)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Code", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblObjAttributes.horizontalHeaderItem(0)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Measured", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblObjAttributes.horizontalHeaderItem(1)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Simulated", None, QtGui.QApplication.UnicodeUTF8))
        item = self.tblObjAttributes.horizontalHeaderItem(2)
        item.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2_2.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Specify Attributes to Optimize:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2_4.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Specify Measured and Simulated Attribute Relations:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label2.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Specify Base Layer Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.Label3.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Specify Simulation Control File:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxControlFile.setToolTip(QtGui.QApplication.translate("OptimizationFileDlg", "Give the filepath and filename of the output shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setToolTip(QtGui.QApplication.translate("OptimizationFileDlg", "Gives dialog box for selecting output filepath and filename.", None, QtGui.QApplication.UnicodeUTF8))
        self.btnBrowse.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.Label3_2.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Specify Optimization Parameters:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Initial Temperature:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Dwell (Evals/Par/T):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Final Temperature:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Max Accepted:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("OptimizationFileDlg", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("OptimizationFileDlg", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Tolerance:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Quench", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Max Evaluations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Boltzmann", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Max Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxTf.setText(QtGui.QApplication.translate("OptimizationFileDlg", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxm.setText(QtGui.QApplication.translate("OptimizationFileDlg", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxT0.setText(QtGui.QApplication.translate("OptimizationFileDlg", "10.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxDwell.setText(QtGui.QApplication.translate("OptimizationFileDlg", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxTolerance.setText(QtGui.QApplication.translate("OptimizationFileDlg", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxMaxEval.setText(QtGui.QApplication.translate("OptimizationFileDlg", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxMaxIter.setText(QtGui.QApplication.translate("OptimizationFileDlg", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxMaxAccept.setText(QtGui.QApplication.translate("OptimizationFileDlg", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxn.setText(QtGui.QApplication.translate("OptimizationFileDlg", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxQuench.setText(QtGui.QApplication.translate("OptimizationFileDlg", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.tbxBoltzmann.setText(QtGui.QApplication.translate("OptimizationFileDlg", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLoad.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Load File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnSave.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Save File", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExit.setText(QtGui.QApplication.translate("OptimizationFileDlg", "Exit", None, QtGui.QApplication.UnicodeUTF8))

