# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_SimOptimizerDlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimOptimizerDlg(object):
    def setupUi(self, SimOptimizerDlg):
        SimOptimizerDlg.setObjectName("SimOptimizerDlg")
        SimOptimizerDlg.resize(561, 471)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SimOptimizerDlg.sizePolicy().hasHeightForWidth())
        SimOptimizerDlg.setSizePolicy(sizePolicy)
        SimOptimizerDlg.setMinimumSize(QtCore.QSize(561, 471))
        SimOptimizerDlg.setMaximumSize(QtCore.QSize(561, 471))
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(SimOptimizerDlg)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 70, 541, 44))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.ProgressBar = QtWidgets.QProgressBar(self.horizontalLayoutWidget_2)
        self.ProgressBar.setObjectName("ProgressBar")
        self.horizontalLayout_3.addWidget(self.ProgressBar)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbxOnlySelected = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cbxOnlySelected.setObjectName("cbxOnlySelected")
        self.verticalLayout.addWidget(self.cbxOnlySelected)
        self.cbxDoGroup = QtWidgets.QCheckBox(self.horizontalLayoutWidget_2)
        self.cbxDoGroup.setObjectName("cbxDoGroup")
        self.verticalLayout.addWidget(self.cbxDoGroup)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.btnRun = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout_3.addWidget(self.btnRun)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(SimOptimizerDlg)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 541, 51))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Label3 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.Label3.setObjectName("Label3")
        self.verticalLayout_3.addWidget(self.Label3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tbxFile = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.tbxFile.setObjectName("tbxFile")
        self.horizontalLayout_2.addWidget(self.tbxFile)
        self.btnBrowse = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout_2.addWidget(self.btnBrowse)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.textSimulation = QtWidgets.QTextBrowser(SimOptimizerDlg)
        self.textSimulation.setGeometry(QtCore.QRect(10, 120, 541, 151))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.textSimulation.setFont(font)
        self.textSimulation.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textSimulation.setObjectName("textSimulation")
        self.btnExit = QtWidgets.QPushButton(SimOptimizerDlg)
        self.btnExit.setGeometry(QtCore.QRect(480, 440, 71, 23))
        self.btnExit.setObjectName("btnExit")
        self.textOptimization = QtWidgets.QTextBrowser(SimOptimizerDlg)
        self.textOptimization.setGeometry(QtCore.QRect(10, 280, 541, 151))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        self.textOptimization.setFont(font)
        self.textOptimization.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.textOptimization.setObjectName("textOptimization")

        self.retranslateUi(SimOptimizerDlg)
        QtCore.QMetaObject.connectSlotsByName(SimOptimizerDlg)

    def retranslateUi(self, SimOptimizerDlg):
        _translate = QtCore.QCoreApplication.translate
        SimOptimizerDlg.setWindowTitle(_translate("SimOptimizerDlg", "Simulation Optimizer"))
        self.cbxOnlySelected.setText(_translate("SimOptimizerDlg", "Selected features only"))
        self.cbxDoGroup.setText(_translate("SimOptimizerDlg", "Group selected features"))
        self.btnRun.setText(_translate("SimOptimizerDlg", "Run"))
        self.Label3.setText(_translate("SimOptimizerDlg", "Specify simulation optimization file:"))
        self.tbxFile.setToolTip(_translate("SimOptimizerDlg", "Give the filepath and filename of the output shapefile"))
        self.btnBrowse.setToolTip(_translate("SimOptimizerDlg", "Gives dialog box for selecting output filepath and filename."))
        self.btnBrowse.setText(_translate("SimOptimizerDlg", "Browse"))
        self.btnExit.setText(_translate("SimOptimizerDlg", "Exit"))

